services:

  db:
    image: postgres:${POSTGRES_VERSION}
    container_name: db_postgres
    restart: always
    shm_size: ${POSTGRES_SHM_SIZE}
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_TIMEZONE: ${TIMEZONE}
      TZ: ${TIMEZONE}
      PGTZ: ${TIMEZONE}
    deploy:
      resources:
        limits:
          cpus: '${POSTGRES_CPU_LIMIT}'
          memory: ${POSTGRES_MEMORY_LIMIT}
        reservations:
          cpus: '${POSTGRES_CPU_RESERVATION}'
          memory: ${POSTGRES_MEMORY_RESERVATION}

  redis:
    image: redis:${REDIS_VERSION}
    container_name: db_redis
    restart: always
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - ./redis_data:/data
    deploy:
      resources:
        limits:
          cpus: '${REDIS_CPU_LIMIT}'
          memory: ${REDIS_MEMORY_LIMIT}
        reservations:
          cpus: '${REDIS_CPU_RESERVATION}'
          memory: ${REDIS_MEMORY_RESERVATION}

networks:
  default:
    name: ${NETWORK_NAME}
    external: true

